/*
 * lib-spfxd — error messages.  All strings live in one pool indexed by
 * 16-bit offsets, avoiding a relocated pointer per message (smaller, and
 * no relocations in libc.so).  Generated by tools/gen-errno.py.
 */
#include <errno.h>
#include <string.h>
#include <stdint.h>
#include "libc.h"

#define NERR 134

static const char pool[] =
	"Success\0Operation not permitted\0No such file or directory\0No such process\0Interrupted"
	" system call\0Input/output error\0No such device or address\0Argument list too long\0Exec"
	" format error\0Bad file descriptor\0No child processes\0Resource temporarily unavailable\0"
	"Cannot allocate memory\0Permission denied\0Bad address\0Block device required\0Device or "
	"resource busy\0File exists\0Invalid cross-device link\0No such device\0Not a directory\0I"
	"s a directory\0Invalid argument\0Too many open files in system\0Too many open files\0Inap"
	"propriate ioctl for device\0Text file busy\0File too large\0No space left on device\0Ille"
	"gal seek\0Read-only file system\0Too many links\0Broken pipe\0Numerical argument out of d"
	"omain\0Numerical result out of range\0Resource deadlock avoided\0File name too long\0No l"
	"ocks available\0Function not implemented\0Directory not empty\0Too many levels of symboli"
	"c links\0No message of desired type\0Identifier removed\0Channel number out of range\0Lev"
	"el 2 not synchronized\0Level 3 halted\0Level 3 reset\0Link number out of range\0Protocol "
	"driver not attached\0No CSI structure available\0Level 2 halted\0Invalid exchange\0Invali"
	"d request descriptor\0Exchange full\0No anode\0Invalid request code\0Invalid slot\0Bad fo"
	"nt file format\0Device not a stream\0No data available\0Timer expired\0Out of streams res"
	"ources\0Machine is not on the network\0Package not installed\0Object is remote\0Link has "
	"been severed\0Advertise error\0Srmount error\0Communication error on send\0Protocol error"
	"\0Multihop attempted\0RFS specific error\0Bad message\0Value too large for defined data t"
	"ype\0Name not unique on network\0File descriptor in bad state\0Remote address changed\0Ca"
	"n not access a needed shared library\0Accessing a corrupted shared library\0.lib section "
	"in a.out corrupted\0Attempting to link in too many shared libraries\0Cannot exec a shared"
	" library directly\0Invalid or incomplete multibyte or wide character\0Interrupted system "
	"call should be restarted\0Streams pipe error\0Too many users\0Socket operation on non-soc"
	"ket\0Destination address required\0Message too long\0Protocol wrong type for socket\0Prot"
	"ocol not available\0Protocol not supported\0Socket type not supported\0Operation not supp"
	"orted\0Protocol family not supported\0Address family not supported by protocol\0Address a"
	"lready in use\0Cannot assign requested address\0Network is down\0Network is unreachable\0"
	"Network dropped connection on reset\0Software caused connection abort\0Connection reset b"
	"y peer\0No buffer space available\0Transport endpoint is already connected\0Transport end"
	"point is not connected\0Cannot send after transport endpoint shutdown\0Too many reference"
	"s: cannot splice\0Connection timed out\0Connection refused\0Host is down\0No route to hos"
	"t\0Operation already in progress\0Operation now in progress\0Stale file handle\0Structure"
	" needs cleaning\0Not a XENIX named type file\0No XENIX semaphores available\0Is a named t"
	"ype file\0Remote I/O error\0Disk quota exceeded\0No medium found\0Wrong medium type\0Oper"
	"ation canceled\0Required key not available\0Key has expired\0Key has been revoked\0Key wa"
	"s rejected by service\0Owner died\0State not recoverable\0Operation not possible due to R"
	"F-kill\0Memory page has hardware error\00\0EPERM\0ENOENT\0ESRCH\0EINTR\0EIO\0ENXIO\0E2BIG"
	"\0ENOEXEC\0EBADF\0ECHILD\0EAGAIN\0ENOMEM\0EACCES\0EFAULT\0ENOTBLK\0EBUSY\0EEXIST\0EXDEV\0"
	"ENODEV\0ENOTDIR\0EISDIR\0EINVAL\0ENFILE\0EMFILE\0ENOTTY\0ETXTBSY\0EFBIG\0ENOSPC\0ESPIPE\0"
	"EROFS\0EMLINK\0EPIPE\0EDOM\0ERANGE\0EDEADLK\0ENAMETOOLONG\0ENOLCK\0ENOSYS\0ENOTEMPTY\0ELO"
	"OP\0ENOMSG\0EIDRM\0ECHRNG\0EL2NSYNC\0EL3HLT\0EL3RST\0ELNRNG\0EUNATCH\0ENOCSI\0EL2HLT\0EBA"
	"DE\0EBADR\0EXFULL\0ENOANO\0EBADRQC\0EBADSLT\0EBFONT\0ENOSTR\0ENODATA\0ETIME\0ENOSR\0ENONE"
	"T\0ENOPKG\0EREMOTE\0ENOLINK\0EADV\0ESRMNT\0ECOMM\0EPROTO\0EMULTIHOP\0EDOTDOT\0EBADMSG\0EO"
	"VERFLOW\0ENOTUNIQ\0EBADFD\0EREMCHG\0ELIBACC\0ELIBBAD\0ELIBSCN\0ELIBMAX\0ELIBEXEC\0EILSEQ\0"
	"ERESTART\0ESTRPIPE\0EUSERS\0ENOTSOCK\0EDESTADDRREQ\0EMSGSIZE\0EPROTOTYPE\0ENOPROTOOPT\0EP"
	"ROTONOSUPPORT\0ESOCKTNOSUPPORT\0EOPNOTSUPP\0EPFNOSUPPORT\0EAFNOSUPPORT\0EADDRINUSE\0EADDR"
	"NOTAVAIL\0ENETDOWN\0ENETUNREACH\0ENETRESET\0ECONNABORTED\0ECONNRESET\0ENOBUFS\0EISCONN\0E"
	"NOTCONN\0ESHUTDOWN\0ETOOMANYREFS\0ETIMEDOUT\0ECONNREFUSED\0EHOSTDOWN\0EHOSTUNREACH\0EALRE"
	"ADY\0EINPROGRESS\0ESTALE\0EUCLEAN\0ENOTNAM\0ENAVAIL\0EISNAM\0EREMOTEIO\0EDQUOT\0ENOMEDIUM"
	"\0EMEDIUMTYPE\0ECANCELED\0ENOKEY\0EKEYEXPIRED\0EKEYREVOKED\0EKEYREJECTED\0EOWNERDEAD\0ENO"
	"TRECOVERABLE\0ERFKILL\0EHWPOISON\0";

static const uint16_t msg_off[NERR] = {
	0, 8, 32, 58, 74, 98, 117, 143, 166, 184,
	204, 223, 256, 279, 297, 309, 331, 355, 367, 393,
	408, 424, 439, 456, 486, 506, 537, 552, 567, 591,
	604, 626, 641, 653, 686, 716, 742, 761, 780, 805,
	825, 65535, 859, 886, 905, 933, 958, 973, 987, 1012,
	1041, 1068, 1083, 1100, 1127, 1141, 1150, 1171, 65535, 1184,
	1205, 1225, 1243, 1257, 1282, 1312, 1334, 1351, 1373, 1389,
	1403, 1431, 1446, 1465, 1484, 1496, 1534, 1561, 1590, 1613,
	1652, 1689, 1721, 1769, 1807, 1857, 1901, 1920, 1935, 1966,
	1995, 2012, 2043, 2066, 2089, 2115, 2139, 2169, 2210, 2233,
	2265, 2281, 2304, 2340, 2373, 2398, 2424, 2464, 2500, 2546,
	2581, 2602, 2621, 2634, 2651, 2681, 2707, 2725, 2750, 2778,
	2808, 2829, 2846, 2866, 2882, 2900, 2919, 2946, 2962, 2983,
	3011, 3022, 3044, 3082,
};

static const uint16_t name_off[NERR] = {
	3113, 3115, 3121, 3128, 3134, 3140, 3144, 3150, 3156, 3164,
	3170, 3177, 3184, 3191, 3198, 3205, 3213, 3219, 3226, 3232,
	3239, 3247, 3254, 3261, 3268, 3275, 3282, 3290, 3296, 3303,
	3310, 3316, 3323, 3329, 3334, 3341, 3349, 3362, 3369, 3376,
	3386, 65535, 3392, 3399, 3405, 3412, 3421, 3428, 3435, 3442,
	3450, 3457, 3464, 3470, 3476, 3483, 3490, 3498, 65535, 3506,
	3513, 3520, 3528, 3534, 3540, 3547, 3554, 3562, 3570, 3575,
	3582, 3588, 3595, 3605, 3613, 3621, 3631, 3640, 3647, 3655,
	3663, 3671, 3679, 3687, 3696, 3703, 3712, 3721, 3728, 3737,
	3750, 3759, 3770, 3782, 3798, 3814, 3825, 3838, 3851, 3862,
	3876, 3885, 3897, 3907, 3920, 3931, 3939, 3947, 3956, 3966,
	3979, 3989, 4002, 4012, 4025, 4034, 4046, 4053, 4061, 4069,
	4077, 4084, 4094, 4101, 4111, 4123, 4133, 4140, 4152, 4164,
	4177, 4188, 4204, 4212,
};

hidden const char *__strerror_lookup(int e)
{
	if (e < 0 || e >= NERR || msg_off[e] == 0xffff) return 0;
	return pool + msg_off[e];
}

const char *strerrordesc_np(int e)
{
	return __strerror_lookup(e);
}

const char *strerrorname_np(int e)
{
	if (e < 0 || e >= NERR || name_off[e] == 0xffff || !e) return 0;
	return pool + name_off[e];
}
