/* lib-spfxd — allocator size classes.  Generated by tools/gen-malloc-classes.py. */
#include "malloc_impl.h"

hidden const uint32_t __malloc_class_size[NCLASS] = {
	16, 32, 48, 64, 80, 96, 112, 128,
	160, 192, 224, 256, 320, 384, 448, 512,
	640, 768, 896, 1024, 1280, 1536, 1792, 2048,
	2560, 3072, 3584, 4096, 5120, 6144, 7168, 8192,
	10240, 12288, 14336, 16384, 20480, 24576, 28672, 32768,
};

hidden const uint8_t __malloc_class_pages[NCLASS] = {
	1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 2, 2, 1, 1,
	3, 3, 2, 2, 5, 3, 4, 4,
	5, 6, 7, 8, 5, 6, 7, 8,
	10, 12, 14, 16, 20, 24, 28, 32,
};
