#!/usr/bin/env python3
"""Generates src/math/math_data.c: constant tables and polynomial
coefficients for lib-spfxd's libm, computed from first principles with
mpmath at 60 significant digits.

Polynomials are near-minimax Chebyshev fits (mpmath.chebyfit) of the
residual function named next to each table; the achieved maximum relative
error of each fit is printed and recorded in the generated file.

    python3 tools/gen-math.py        (requires mpmath)
"""
import mpmath as mp
from mpmath import mpf

mp.mp.dps = 60

out = []
def emit(s=""):
    out.append(s)

def hexd(x):
    """Round an mpf to the nearest double and print it as a C hex float."""
    return float(x).hex()

def dd(x):
    """Split x into a double-double (hi, lo)."""
    hi = float(x)
    lo = float(x - mpf(hi))
    return hi, lo

def arr(name, vals, ctype="double", per=3):
    emit("hidden const %s %s[%d] = {" % (ctype, name, len(vals)))
    row = []
    for v in vals:
        row.append(v if isinstance(v, str) else hexd(v))
        if len(row) == per:
            emit("\t" + ", ".join(row) + ","); row = []
    if row: emit("\t" + ", ".join(row) + ",")
    emit("};")

def fit(f, a, b, n, name, note):
    """Fit f on [a,b] with a degree-n polynomial; returns coefficients in
    increasing order, rounded to double, and reports the relative error of
    the rounded polynomial."""
    coeffs, err = mp.chebyfit(f, [a, b], n + 1, error=True)
    coeffs = coeffs[::-1]                     # increasing degree
    rc = [float(c) for c in coeffs]
    # measure the error of the double-rounded coefficients
    worst = mpf(0)
    for i in range(2001):
        x = a + (b - a) * i / 2000
        fx = f(x)
        px = mpf(0)
        for c in reversed(rc):
            px = px * x + c
        if fx != 0:
            e = abs((px - fx) / fx)
            worst = max(worst, e)
    print("%-14s deg %2d on [%s, %s]: rel err %.3e  (%s)" % (name, n, mp.nstr(a, 6), mp.nstr(b, 6), float(worst), note))
    emit("/* %s: %s on [%s, %s], degree %d, max rel. error %.2e */" %
         (name, note, mp.nstr(a, 8), mp.nstr(b, 8), n, float(worst)))
    arr(name, rc, per=3)
    return rc

emit("/*")
emit(" * lib-spfxd — libm constant tables and polynomial coefficients.")
emit(" * Generated by tools/gen-math.py with mpmath; do not edit by hand.")
emit(" */")
emit('#include <stdint.h>')
emit('#include "libc.h"')
emit("")

# ---------------------------------------------------------------- exp
emit("/* 2^(j/32), j = 0..31, as double-double (hi, lo) pairs */")
vals = []
for j in range(32):
    h, l = dd(mp.power(2, mpf(j) / 32))
    vals += [h, l]
arr("__exp_tab", vals, per=2)
ln2 = mp.log(2)
# ln2/32 split: hi keeps 37 significant bits so k*hi is exact for |k| < 2^16
def trunc_bits(x, bits):
    m, e = mp.frexp(x)
    m = mp.floor(m * 2**bits) / 2**bits
    return mp.ldexp(m, e)
l32 = ln2 / 32
l32_hi = trunc_bits(l32, 37)
l32_lo = l32 - l32_hi
emit("hidden const double __exp_ln2_32[2] = { %s, %s };" % (hexd(l32_hi), hexd(l32_lo)))
emit("hidden const double __exp_inv_ln2_32 = %s;" % hexd(32 / ln2))
r = ln2 / 64 * mpf("1.02")
fit(lambda x: (mp.expm1(x) - x - x * x / 2) / x**3 if x != 0 else mpf(1) / 6,
    -r, r, 4, "__expm1_poly", "(expm1(r) - r - r^2/2) / r^3")

# ---------------------------------------------------------------- log
# 128 intervals of m in [0.75, 1.5): index from the top 7 mantissa bits
# after biasing by 0.75.  inv_i ~ 1/center with 20 significant bits; the
# two intervals adjacent to 1.0 use inv = 1 exactly.
emit("")
emit("/* log tables: inverse centers and -log(inverse) as double-double */")
invs, logc = [], []
off = mpf("0.75")
import struct
def bits(x): return struct.unpack("<Q", struct.pack("<d", x))[0]
def frombits(b): return struct.unpack("<d", struct.pack("<Q", b))[0]
OFF = bits(0.75)
max_r = mpf(0)
for i in range(128):
    # interval i: mantissa bits of (u - OFF) top 7 bits == i
    lo_b = OFF + (i << 45)
    lo = mpf(frombits(lo_b if (lo_b >> 52) == (OFF >> 52) else lo_b))
    # u - OFF top 7 bits index; reconstruct interval endpoints
    t0 = (i << 45)
    t1 = ((i + 1) << 45)
    a = mpf(frombits(OFF + t0)) if True else None
    # translate back to [0.75, 1.5) by removing the exponent carry
    def norm(u):
        tmp = u - OFF
        k = tmp >> 52 if tmp >= 0 else -((-tmp + (1 << 52) - 1) >> 52)
        return frombits(u - (k << 52))
    A = mpf(norm(OFF + t0))
    B = mpf(norm(OFF + t1 - 1))
    c = (A + B) / 2
    if A <= 1 <= B or (abs(B - 1) < mpf(2)**-6 and B < 1) or (abs(A - 1) < mpf(2)**-6 and A > 1 and A - 1 < mpf("0.008")):
        inv = mpf(1)
    else:
        inv = trunc_bits(1 / c, 20)
    invs.append(float(inv))
    lc = -mp.log(mpf(float(inv)))
    h, l = dd(lc)
    logc += [h, l]
    for x in (A, B):
        max_r = max(max_r, abs(x * mpf(float(inv)) - 1))
arr("__log_inv", invs, per=4)
arr("__log_logc", logc, per=2)
print("log: max |r| = %.5g" % float(max_r))
lnh = trunc_bits(ln2, 42)
emit("hidden const double __log_ln2[2] = { %s, %s };" % (hexd(lnh), hexd(ln2 - lnh)))
rm = max_r * mpf("1.05")
fit(lambda x: (mp.log1p(x) - x + x * x / 2) / x**3 if x != 0 else mpf(1) / 3,
    -rm, rm, 5, "__log1p_poly", "(log1p(r) - r + r^2/2) / r^3")
for name, val in (("__inv_ln2", 1 / ln2), ("__inv_ln10", 1 / mp.log(10)),
                  ("__ln10", mp.log(10)), ("__log2_10", mp.log(10, 2)), ("__ln2", ln2)):
    h, l = dd(val)
    emit("hidden const double %s[2] = { %s, %s };" % (name, hexd(h), hexd(l)))

# ---------------------------------------------------------------- trig
emit("")
pio4 = mp.pi / 4
fit(lambda x: (mp.sin(mp.sqrt(x)) - mp.sqrt(x)) / mp.sqrt(x)**3 if x != 0 else -mpf(1) / 6,
    mpf(0), pio4**2, 6, "__sin_poly", "(sin(r) - r) / r^3 in z = r^2")
fit(lambda x: (mp.cos(mp.sqrt(x)) - 1 + x / 2) / x**2 if x != 0 else mpf(1) / 24,
    mpf(0), pio4**2, 6, "__cos_poly", "(cos(r) - 1 + r^2/2) / r^4 in z = r^2")
# pi/2 split into 33-bit pieces (n * piece exact for |n| < 2^20)
pio2 = mp.pi / 2
p1 = trunc_bits(pio2, 33)
p2 = trunc_bits(pio2 - p1, 33)
p3 = trunc_bits(pio2 - p1 - p2, 33)
p3lo = pio2 - p1 - p2 - p3
emit("hidden const double __pio2_split[4] = { %s, %s, %s, %s };" % (hexd(p1), hexd(p2), hexd(p3), hexd(p3lo)))
h, l = dd(pio2)
emit("hidden const double __pio2_dd[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(mp.pi)
emit("hidden const double __pi_dd[2] = { %s, %s };" % (hexd(h), hexd(l)))
emit("hidden const double __two_over_pi = %s;" % hexd(2 / mp.pi))
# bits of 2/pi: 24 words of 64 bits after the binary point (1536 bits)
mp.mp.dps = 600
tp = 2 / mp.pi
words = []
x = tp
for i in range(24):
    x *= mpf(2)**64
    w = int(mp.floor(x))
    words.append(w)
    x -= w
mp.mp.dps = 60
emit("/* 2/pi = 0.b0 b1 b2 ... with b_i the 64-bit words below (1536 bits) */")
emit("hidden const uint64_t __two_over_pi_bits[24] = {")
for i in range(0, 24, 3):
    emit("\t" + ", ".join("0x%016xULL" % w for w in words[i:i + 3]) + ",")
emit("};")

# ---------------------------------------------------------------- atan
emit("")
vals = []
for k in range(17):
    h, l = dd(mp.atan(mpf(k) / 16))
    vals += [h, l]
arr("__atan_tab", vals, per=2)
u = mpf(1) / 32 * mpf("1.1")
fit(lambda x: (mp.atan(mp.sqrt(x)) - mp.sqrt(x)) / mp.sqrt(x)**3 if x != 0 else -mpf(1) / 3,
    mpf(0), u * u, 5, "__atan_poly", "(atan(u) - u) / u^3 in z = u^2")

# ---------------------------------------------------------------- hyperbolic
emit("")
fit(lambda x: (mp.sinh(mp.sqrt(x)) - mp.sqrt(x)) / mp.sqrt(x)**3 if x != 0 else mpf(1) / 6,
    mpf(0), mpf("0.5")**2, 6, "__sinh_poly", "(sinh(x) - x) / x^3 in z = x^2, |x| <= 0.5")
fit(lambda x: (mp.tanh(mp.sqrt(x)) - mp.sqrt(x)) / mp.sqrt(x)**3 if x != 0 else -mpf(1) / 3,
    mpf(0), mpf("0.55")**2, 11, "__tanh_poly", "(tanh(x) - x) / x^3 in z = x^2, |x| <= 0.55")

# ---------------------------------------------------------------- erf
emit("")
fit(lambda x: (mp.erf(mp.sqrt(x)) / mp.sqrt(x)) if x != 0 else 2 / mp.sqrt(mp.pi),
    mpf(0), mpf("0.84375")**2, 11, "__erf_poly", "erf(x)/x in z = x^2, |x| <= 0.84375")
# erfc(x) = exp(-x^2) * R(x); fit R on pieces in t = 1/x (for x >= 2) or x
pieces = [(mpf("0.84375"), mpf("1.25"), 14), (mpf("1.25"), mpf("2"), 15), (mpf("2"), mpf("3"), 15),
          (mpf("3"), mpf("4.5"), 16), (mpf("4.5"), mpf("6.5"), 16), (mpf("6.5"), mpf("10"), 14),
          (mpf("10"), mpf("28"), 10)]
emit("/* erfc(x) = exp(-x^2) * P_k(x - a_k) on [a_k, b_k) */")
emit("hidden const double __erfc_bounds[%d] = { %s };" % (len(pieces) + 1,
     ", ".join([hexd(p[0]) for p in pieces] + [hexd(pieces[-1][1])])))
emit("hidden const int __erfc_degree[%d] = { %s };" % (len(pieces), ", ".join(str(p[2]) for p in pieces)))
allc = []
starts = []
for (a, b, n) in pieces:
    f = (lambda a_: (lambda t: mp.erfc(t + a_) * mp.exp((t + a_)**2)))(a)
    starts.append(len(allc))
    coeffs, err = mp.chebyfit(f, [0, b - a], n + 1, error=True)
    coeffs = coeffs[::-1]
    rc = [float(c) for c in coeffs]
    worst = mpf(0)
    for i in range(801):
        t = (b - a) * i / 800
        fx = f(t)
        px = mpf(0)
        for c in reversed(rc): px = px * t + c
        worst = max(worst, abs((px - fx) / fx))
    print("erfc piece [%s,%s] deg %d rel err %.3e" % (mp.nstr(a, 5), mp.nstr(b, 5), n, float(worst)))
    allc += rc
emit("hidden const int __erfc_start[%d] = { %s };" % (len(pieces), ", ".join(str(s) for s in starts)))
arr("__erfc_coef", allc, per=3)

# ---------------------------------------------------------------- lgamma
emit("")
euler = mp.euler
fit(lambda t: mp.loggamma(1 + t) / t if t != 0 else -euler,
    mpf("-0.25"), mpf("0.25"), 18, "__lgamma1_poly", "lgamma(1+t)/t, |t| <= 0.25")
fit(lambda t: mp.loggamma(2 + t) / t if t != 0 else 1 - euler,
    mpf("-0.75"), mpf("0.75"), 24, "__lgamma2_poly", "lgamma(2+t)/t, |t| <= 0.75")
# Stirling series coefficients B_2k / (2k (2k-1)), k = 1..10
st = [mp.bernoulli(2 * k) / (2 * k * (2 * k - 1)) for k in range(1, 11)]
arr("__stirling", st, per=3)
h, l = dd(mp.log(2 * mp.pi) / 2)
emit("hidden const double __half_log_2pi[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(mp.log(mp.pi))
emit("hidden const double __log_pi[2] = { %s, %s };" % (hexd(h), hexd(l)))
emit("hidden const double __euler_gamma = %s;" % hexd(euler))
h, l = dd(2 / mp.sqrt(mp.pi))
emit("hidden const double __two_over_sqrtpi[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(1 / mp.sqrt(mp.pi))
emit("hidden const double __inv_sqrtpi[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(mp.sqrt(2 / mp.pi))
emit("hidden const double __sqrt_2_over_pi[2] = { %s, %s };" % (hexd(h), hexd(l)))

# ---------------------------------------------------------------- long double
emit("")
emit("/* long double constants (x87 extended) as decimal literals with 21 digits */")
def ldlit(x):
    return mp.nstr(x, 25, strip_zeros=False) + "L"
mp.mp.dps = 80
pio2 = mp.pi / 2
# pi/2 split into 32-bit pieces for long double reduction
def trunc_bits80(x, bits):
    m, e = mp.frexp(x)
    m = mp.floor(m * 2**bits) / 2**bits
    return mp.ldexp(m, e)
q1 = trunc_bits80(pio2, 32)
q2 = trunc_bits80(pio2 - q1, 32)
q3 = trunc_bits80(pio2 - q1 - q2, 32)
q4 = pio2 - q1 - q2 - q3
emit("hidden const long double __pio2l_split[4] = { %s, %s, %s, %s };" % (ldlit(q1), ldlit(q2), ldlit(q3), ldlit(q4)))
emit("hidden const long double __two_over_pil = %s;" % ldlit(2 / mp.pi))
emit("hidden const long double __pio2l = %s;" % ldlit(pio2))
emit("hidden const long double __pio2l_lo = %s;" % ldlit(pio2 - mpf(mp.nstr(pio2, 25))))
lg2e = 1 / mp.log(2)
e_hi = trunc_bits80(lg2e, 32)
emit("hidden const long double __log2el[2] = { %s, %s };" % (ldlit(e_hi), ldlit(lg2e - e_hi)))
l10 = mp.log(10, 2)
t_hi = trunc_bits80(l10, 32)
emit("hidden const long double __log2_10l[2] = { %s, %s };" % (ldlit(t_hi), ldlit(l10 - t_hi)))

open("src/math/math_data.c", "w").write("\n".join(out) + "\n")
print("wrote src/math/math_data.c")
