#!/usr/bin/env python3
# Regenerates src/memory/malloc_classes.c: size classes and span sizes.
# Classes: 16..128 in 16-byte steps, then four classes per power of two up
# to 32 KiB.  Span length (pages) per class is the smallest that wastes at
# most 1/32 of the span while holding enough objects to amortize span
# management, falling back to the least wasteful length up to 32 pages.
sizes = list(range(16, 129, 16))
e = 128
while e < 32768:
    for q in range(1, 5):
        sizes.append(e + q * e // 4)
    e *= 2
assert len(sizes) == 40 and sizes[-1] == 32768
pages = []
for cs in sizes:
    min_objs = 8 if cs <= 4096 else 4
    best = None
    choice = None
    for k in range(1, 33):
        n = k * 4096 // cs
        if n < min_objs or n > 65535:
            continue
        waste = (k * 4096 - n * cs) / (k * 4096)
        if waste <= 1 / 32:
            choice = k
            break
        if best is None or waste < best[0] - 1e-12:
            best = (waste, k)
    pages.append(choice if choice else best[1])
out = ["/* lib-spfxd — allocator size classes.  Generated by tools/gen-malloc-classes.py. */",
       '#include "malloc_impl.h"', "",
       "hidden const uint32_t __malloc_class_size[NCLASS] = {"]
for i in range(0, 40, 8):
    out.append("\t" + ", ".join(str(s) for s in sizes[i:i+8]) + ",")
out.append("};")
out.append("")
out.append("hidden const uint8_t __malloc_class_pages[NCLASS] = {")
for i in range(0, 40, 8):
    out.append("\t" + ", ".join(str(p) for p in pages[i:i+8]) + ",")
out.append("};")
open("src/memory/malloc_classes.c", "w").write("\n".join(out) + "\n")
for cs, k in zip(sizes, pages):
    n = k * 4096 // cs
    print(cs, k, n, "%.3f" % ((k * 4096 - n * cs) / (k * 4096)))
