#!/usr/bin/env python3
"""Generates src/iconv/iconv_tables.c: the upper halves (bytes 0x80-0xFF)
of the single-byte character sets supported by lib-spfxd's iconv, taken
from Python's codec definitions.  0xFFFD marks an unassigned byte.

    python3 tools/gen-iconv.py
"""
import codecs

# (canonical name, python codec, aliases)
CHARSETS = [
    ("ISO-8859-2", "iso8859_2", ["LATIN2", "ISO8859-2", "ISO_8859-2"]),
    ("ISO-8859-3", "iso8859_3", ["LATIN3", "ISO8859-3"]),
    ("ISO-8859-4", "iso8859_4", ["LATIN4", "ISO8859-4"]),
    ("ISO-8859-5", "iso8859_5", ["CYRILLIC", "ISO8859-5"]),
    ("ISO-8859-6", "iso8859_6", ["ARABIC", "ISO8859-6"]),
    ("ISO-8859-7", "iso8859_7", ["GREEK", "ISO8859-7"]),
    ("ISO-8859-8", "iso8859_8", ["HEBREW", "ISO8859-8"]),
    ("ISO-8859-9", "iso8859_9", ["LATIN5", "ISO8859-9"]),
    ("ISO-8859-10", "iso8859_10", ["LATIN6", "ISO8859-10"]),
    ("ISO-8859-11", "iso8859_11", ["ISO8859-11", "TIS-620"]),
    ("ISO-8859-13", "iso8859_13", ["LATIN7", "ISO8859-13"]),
    ("ISO-8859-14", "iso8859_14", ["LATIN8", "ISO8859-14"]),
    ("ISO-8859-15", "iso8859_15", ["LATIN9", "ISO8859-15", "LATIN-9"]),
    ("ISO-8859-16", "iso8859_16", ["LATIN10", "ISO8859-16"]),
    ("WINDOWS-1250", "cp1250", ["CP1250"]),
    ("WINDOWS-1251", "cp1251", ["CP1251"]),
    ("WINDOWS-1252", "cp1252", ["CP1252"]),
    ("WINDOWS-1253", "cp1253", ["CP1253"]),
    ("WINDOWS-1254", "cp1254", ["CP1254"]),
    ("WINDOWS-1255", "cp1255", ["CP1255"]),
    ("WINDOWS-1256", "cp1256", ["CP1256"]),
    ("WINDOWS-1257", "cp1257", ["CP1257"]),
    ("WINDOWS-1258", "cp1258", ["CP1258"]),
    ("KOI8-R", "koi8_r", []),
    ("KOI8-U", "koi8_u", []),
    ("CP437", "cp437", ["IBM437"]),
    ("CP850", "cp850", ["IBM850"]),
    ("CP866", "cp866", ["IBM866"]),
    ("MACINTOSH", "mac_roman", ["MACROMAN", "MAC"]),
]

out = []
out.append("/*")
out.append(" * lib-spfxd — single-byte character set tables for iconv.")
out.append(" * Generated by tools/gen-iconv.py; do not edit by hand.")
out.append(" * Each table maps bytes 0x80..0xFF to Unicode (0xFFFD: unassigned);")
out.append(" * bytes below 0x80 are ASCII in every set listed here.")
out.append(" */")
out.append('#include <stdint.h>')
out.append('#include "iconv_impl.h"')
out.append("")
for name, codec, aliases in CHARSETS:
    vals = []
    for b in range(0x80, 0x100):
        try:
            u = bytes([b]).decode(codec)
            assert len(u) == 1
            vals.append(ord(u))
        except UnicodeDecodeError:
            vals.append(0xFFFD)
    # ASCII half must be identity
    for b in range(0x80):
        assert bytes([b]).decode(codec) == chr(b), (name, b)
    cname = "t_" + name.replace("-", "_").lower()
    out.append("static const uint16_t %s[128] = {" % cname)
    for i in range(0, 128, 8):
        out.append("\t" + ", ".join("0x%04x" % v for v in vals[i:i + 8]) + ",")
    out.append("};")
out.append("")
out.append("hidden const struct sbcs __iconv_sbcs[] = {")
for name, codec, aliases in CHARSETS:
    cname = "t_" + name.replace("-", "_").lower()
    al = "".join(a + "\\0" for a in aliases)
    out.append('\t{ "%s", "%s", %s },' % (name, al, cname))
out.append("\t{ 0, 0, 0 },")
out.append("};")
open("src/iconv/iconv_tables.c", "w").write("\n".join(out) + "\n")
print("wrote src/iconv/iconv_tables.c (%d charsets)" % len(CHARSETS))
