#!/usr/bin/env python3
# Regenerates src/ctype/ctype_table.c (C/POSIX classification of ASCII).
U,L,D,S,P,C,X,B,PR,A,G,AN=0x1,0x2,0x4,0x8,0x10,0x20,0x40,0x80,0x100,0x200,0x400,0x800
def cls(c):
    v=0
    if 65<=c<=90: v|=U|A|AN
    if 97<=c<=122: v|=L|A|AN
    if 48<=c<=57: v|=D|AN
    if c in (32,9,10,11,12,13): v|=S
    if c<32 or c==127: v|=C
    if (48<=c<=57) or (65<=c<=70) or (97<=c<=102): v|=X
    if c in (32,9): v|=B
    if 32<=c<=126: v|=PR
    if 33<=c<=126: v|=G
    if 33<=c<=126 and not (48<=c<=57 or 65<=c<=90 or 97<=c<=122): v|=P
    return v
vals=[0]*384
for c in range(128): vals[c+128]=cls(c)
out=["/* lib-spfxd — C/POSIX locale character classification table.",
" * Generated by the script in tools/gen-ctype.py; indexed by c + 128 so that",
" * EOF (-1) and negative plain-char values are valid indices. */",
"#include <ctype.h>","","const unsigned short __spfxd_ctype_tab[384] = {"]
for i in range(0,384,8):
    out.append("\t"+", ".join("0x%03x"%v for v in vals[i:i+8])+",")
out.append("};")
open("src/ctype/ctype_table.c","w").write("\n".join(out)+"\n")
