#!/usr/bin/env python3
"""Generates src/stdlib/pow5_table.c: 128-bit approximations of 5^q for
q = -342..308, used by strtod's Eisel-Lemire fast path.

Each entry is the 128-bit window starting at the leading one bit of 5^q
(exact integer arithmetic):
  q >= 0: 5^q shifted so its top bit is bit 127, then truncated;
  q <  0: for -27 <= q (5^-q < 2^64) floor(2^(z+127) / 5^-q) + 1, which
          has exactly 128 bits; below that floor(2^(2z+128) / 5^-q) + 1
          truncated to 128 bits.  (z = bit length of 5^-q.)  This is the
          table the algorithm's error analysis is stated for.

    python3 tools/gen-pow5.py
"""
QMIN, QMAX = -342, 308
out = []
for q in range(QMIN, QMAX + 1):
    if q >= 0:
        v = 5 ** q
        while v < (1 << 127):
            v <<= 1
        while v >= (1 << 128):
            v >>= 1
    else:
        p5 = 5 ** -q
        z = p5.bit_length()           # 2^(z-1) < 5^-q < 2^z
        if q >= -27:
            # 5^-q fits in 64 bits: exactly 128 bits, rounded up
            v = (1 << (z + 127)) // p5 + 1
        else:
            v = (1 << (2 * z + 128)) // p5 + 1
            while v >= (1 << 128):
                v >>= 1
    out.append((v >> 64, v & ((1 << 64) - 1)))

lines = [
    "/*",
    " * lib-spfxd -- 128-bit approximations of 5^q, q = %d..%d, for the" % (QMIN, QMAX),
    " * Eisel-Lemire path of strtod.  Generated by tools/gen-pow5.py from",
    " * exact integer arithmetic; do not edit by hand.",
    " */",
    "#include <stdint.h>",
    '#include "libc.h"',
    "",
    "hidden const uint64_t __pow5_128[%d] = {" % (2 * len(out)),
]
for hi, lo in out:
    lines.append("\t0x%016xULL, 0x%016xULL," % (hi, lo))
lines.append("};")
open("src/stdlib/pow5_table.c", "w").write("\n".join(lines) + "\n")
print("wrote src/stdlib/pow5_table.c (%d entries)" % len(out))
