#!/usr/bin/env python3
"""Generates src/math/math_data.c: constant tables and polynomial
coefficients for lib-spfxd's libm, computed from first principles with
mpmath at 60 significant digits.

Polynomials are near-minimax Chebyshev fits (mpmath.chebyfit) of the
residual function named next to each table; the achieved maximum relative
error of each fit is printed and recorded in the generated file.

    python3 tools/gen-math.py        (requires mpmath)
"""
import mpmath as mp
from mpmath import mpf

mp.mp.dps = 60

out = []
def emit(s=""):
    out.append(s)

def hexd(x):
    """Round an mpf to the nearest double and print it as a C hex float."""
    return float(x).hex()

def dd(x):
    """Split x into a double-double (hi, lo)."""
    hi = float(x)
    lo = float(x - mpf(hi))
    return hi, lo

def arr(name, vals, ctype="double", per=3):
    emit("hidden const %s %s[%d] = {" % (ctype, name, len(vals)))
    row = []
    for v in vals:
        row.append(v if isinstance(v, str) else hexd(v))
        if len(row) == per:
            emit("\t" + ", ".join(row) + ","); row = []
    if row: emit("\t" + ", ".join(row) + ",")
    emit("};")

def fit(f, a, b, n, name, note):
    """Fit f on [a,b] with a degree-n polynomial; returns coefficients in
    increasing order, rounded to double, and reports the relative error of
    the rounded polynomial."""
    coeffs, err = mp.chebyfit(f, [a, b], n + 1, error=True)
    coeffs = coeffs[::-1]                     # increasing degree
    rc = [float(c) for c in coeffs]
    # measure the error of the double-rounded coefficients
    worst = mpf(0)
    for i in range(2001):
        x = a + (b - a) * i / 2000
        fx = f(x)
        px = mpf(0)
        for c in reversed(rc):
            px = px * x + c
        if fx != 0:
            e = abs((px - fx) / fx)
            worst = max(worst, e)
    print("%-14s deg %2d on [%s, %s]: rel err %.3e  (%s)" % (name, n, mp.nstr(a, 6), mp.nstr(b, 6), float(worst), note))
    emit("/* %s: %s on [%s, %s], degree %d, max rel. error %.2e */" %
         (name, note, mp.nstr(a, 8), mp.nstr(b, 8), n, float(worst)))
    arr(name, rc, per=3)
    return rc

emit("/*")
emit(" * lib-spfxd — libm constant tables and polynomial coefficients.")
emit(" * Generated by tools/gen-math.py with mpmath; do not edit by hand.")
emit(" */")
emit('#include <stdint.h>')
emit('#include "libc.h"')
emit("")

# ---------------------------------------------------------------- exp
emit("/* 2^(j/32), j = 0..31, as double-double (hi, lo) pairs */")
vals = []
for j in range(32):
    h, l = dd(mp.power(2, mpf(j) / 32))
    vals += [h, l]
arr("__exp_tab", vals, per=2)
ln2 = mp.log(2)
# ln2/32 split: hi keeps 37 significant bits so k*hi is exact for |k| < 2^16
def trunc_bits(x, bits):
    m, e = mp.frexp(x)
    m = mp.floor(m * 2**bits) / 2**bits
    return mp.ldexp(m, e)
l32 = ln2 / 32
l32_hi = trunc_bits(l32, 37)
l32_lo = l32 - l32_hi
emit("hidden const double __exp_ln2_32[2] = { %s, %s };" % (hexd(l32_hi), hexd(l32_lo)))
emit("hidden const double __exp_inv_ln2_32 = %s;" % hexd(32 / ln2))
r = ln2 / 64 * mpf("1.02")
fit(lambda x: (mp.expm1(x) - x - x * x / 2) / x**3 if x != 0 else mpf(1) / 6,
    -r, r, 4, "__expm1_poly", "(expm1(r) - r - r^2/2) / r^3")

# exp fast path: 2^(j/128) as dd, ln2/128 split with a 35-bit high part
# (k ln2hi exact for |k| < 2^17, i.e. |x| < 709.8) and a minimax fit of
# (exp(r) - 1 - r) / r^2 for |r| <= ln2/256 (with margin).
emit("/* fast exp: 2^(j/128), j = 0..127, as double-double (hi, lo) pairs */")
vals = []
for j in range(128):
    h, l = dd(mp.power(2, mpf(j) / 128))
    vals += [h, l]
arr("__exp128_tab", vals, per=2)
l128 = ln2 / 128
l128_hi = trunc_bits(l128, 35)
emit("hidden const double __exp128_ln2[2] = { %s, %s };" % (hexd(l128_hi), hexd(l128 - l128_hi)))
emit("hidden const double __exp128_inv = %s;" % hexd(128 / ln2))
r = ln2 / 256 * mpf("1.05")
fit(lambda x: (mp.expm1(x) - x) / x**2 if x != 0 else mpf(1) / 2,
    -r, r, 4, "__exp128_poly", "(exp(r) - 1 - r) / r^2")

# ---------------------------------------------------------------- log
# The argument is normalized to m in [0.75, 1.5) by subtracting the bit
# pattern of 0.75 from the bit pattern of x: the integer exponent comes
# from the top bits of the difference and the index i from its next 7
# bits.  Interval i is [0.75 + i/256, 0.75 + (i+1)/256) for i < 64 and
# [1 + (i-64)/128, 1 + (i-63)/128) for i >= 64.  inv_i ~ 1/center; the two
# intervals touching 1.0 use inv = 1 so that log is exactly log1p(m - 1)
# there (no cancellation for x near 1).
emit("")
emit("/* log tables: inverse centers and -log(inverse) as double-double */")
invs, logc = [], []
max_r = mpf(0)
for i in range(128):
    if i < 64:
        A = mpf("0.75") + mpf(i) / 256; B = A + mpf(1) / 256
    else:
        A = 1 + mpf(i - 64) / 128; B = A + mpf(1) / 128
    if i in (63, 64):
        inv = mpf(1)
    else:
        inv = trunc_bits(2 / (A + B), 24)
    invs.append(float(inv))
    h, l = dd(-mp.log(inv))
    logc += [h, l]
    for x in (A, B):
        max_r = max(max_r, abs(x * inv - 1))
arr("__log_inv", invs, per=4)
arr("__log_logc", logc, per=2)
print("log: max |r| = %.5g" % float(max_r))
lnh = trunc_bits(ln2, 42)
emit("hidden const double __log_ln2[2] = { %s, %s };" % (hexd(lnh), hexd(ln2 - lnh)))
rm = max_r * mpf("1.02")
fit(lambda x: (mp.log1p(x) - x + x * x / 2) / x**3 if x != 0 else mpf(1) / 3,
    -rm, rm, 7, "__log1p_poly", "(log1p(r) - r + r^2/2) / r^3")
for name, val in (("__inv_ln2", 1 / ln2), ("__inv_ln10", 1 / mp.log(10)),
                  ("__ln10", mp.log(10)), ("__log2_10", mp.log(10, 2)), ("__ln2", ln2),
                  ("__log10_2", mp.log10(2))):
    h, l = dd(val)
    emit("hidden const double %s[2] = { %s, %s };" % (name, hexd(h), hexd(l)))

# ---------------------------------------------------------------- trig
emit("")
pio4 = mp.pi / 4
fit(lambda x: (mp.sin(mp.sqrt(x)) - mp.sqrt(x)) / mp.sqrt(x)**3 if x != 0 else -mpf(1) / 6,
    mpf(0), pio4**2, 6, "__sin_poly", "(sin(r) - r) / r^3 in z = r^2")
fit(lambda x: (mp.cos(mp.sqrt(x)) - 1 + x / 2) / x**2 if x != 0 else mpf(1) / 24,
    mpf(0), pio4**2, 6, "__cos_poly", "(cos(r) - 1 + r^2/2) / r^4 in z = r^2")
# pi/2 split into 33-bit pieces (n * piece exact for |n| < 2^20)
pio2 = mp.pi / 2
p1 = trunc_bits(pio2, 33)
p2 = trunc_bits(pio2 - p1, 33)
p3 = trunc_bits(pio2 - p1 - p2, 33)
p3lo = pio2 - p1 - p2 - p3
emit("hidden const double __pio2_split[4] = { %s, %s, %s, %s };" % (hexd(p1), hexd(p2), hexd(p3), hexd(p3lo)))
h, l = dd(pio2)
emit("hidden const double __pio2_dd[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(mp.pi)
emit("hidden const double __pi_dd[2] = { %s, %s };" % (hexd(h), hexd(l)))
emit("hidden const double __two_over_pi = %s;" % hexd(2 / mp.pi))
# bits of 2/pi: 264 words of 64 bits after the binary point (16896 bits),
# enough for Payne-Hanek reduction of the largest long double
NW = 264
mp.mp.dps = 5200
tp = 2 / mp.pi
words = []
x = tp
for i in range(NW):
    x *= mpf(2)**64
    w = int(mp.floor(x))
    words.append(w)
    x -= w
mp.mp.dps = 60
emit("/* 2/pi = 0.w0 w1 w2 ... with w_i the 64-bit words below */")
emit("hidden const uint64_t __two_over_pi_bits[%d] = {" % NW)
for i in range(0, NW, 3):
    emit("\t" + ", ".join("0x%016xULL" % w for w in words[i:i + 3]) + ",")
emit("};")

# ---------------------------------------------------------------- atan
emit("")
vals = []
for k in range(17):
    h, l = dd(mp.atan(mpf(k) / 16))
    vals += [h, l]
arr("__atan_tab", vals, per=2)
u = mpf(1) / 32 * mpf("1.1")
fit(lambda x: (mp.atan(mp.sqrt(x)) - mp.sqrt(x)) / mp.sqrt(x)**3 if x != 0 else -mpf(1) / 3,
    mpf(0), u * u, 5, "__atan_poly", "(atan(u) - u) / u^3 in z = u^2")

# ---------------------------------------------------------------- hyperbolic
emit("")
fit(lambda x: (mp.sinh(mp.sqrt(x)) - mp.sqrt(x)) / mp.sqrt(x)**3 if x != 0 else mpf(1) / 6,
    mpf(0), mpf("0.5")**2, 6, "__sinh_poly", "(sinh(x) - x) / x^3 in z = x^2, |x| <= 0.5")
fit(lambda x: (mp.tanh(mp.sqrt(x)) - mp.sqrt(x)) / mp.sqrt(x)**3 if x != 0 else -mpf(1) / 3,
    mpf(0), mpf("0.55")**2, 11, "__tanh_poly", "(tanh(x) - x) / x^3 in z = x^2, |x| <= 0.55")

# ---------------------------------------------------------------- erf
emit("")
fit(lambda x: (mp.erf(mp.sqrt(x)) / mp.sqrt(x)) if x != 0 else 2 / mp.sqrt(mp.pi),
    mpf(0), mpf("0.84375")**2, 11, "__erf_poly", "erf(x)/x in z = x^2, |x| <= 0.84375")
# erfc(x) = exp(-x^2) * R(x); fit R on pieces in t = 1/x (for x >= 2) or x
pieces = [(mpf("0"), mpf("0.40625"), 14), (mpf("0.40625"), mpf("0.84375"), 15), (mpf("0.84375"), mpf("1.25"), 14),
          (mpf("1.25"), mpf("2"), 15), (mpf("2"), mpf("3"), 15),
          (mpf("3"), mpf("4.5"), 16), (mpf("4.5"), mpf("5.5"), 16), (mpf("5.5"), mpf("6.5"), 16)]
emit("/* erfc(x) = exp(-x^2) * P_k(x - a_k) on [a_k, a_k+1) */")
emit("hidden const double __erfc_bounds[%d] = { %s };" % (len(pieces) + 1,
     ", ".join([hexd(p[0]) for p in pieces] + [hexd(pieces[-1][1])])))
emit("hidden const int __erfc_degree[%d] = { %s };" % (len(pieces), ", ".join(str(p[2]) for p in pieces)))
allc = []
starts = []
los = []
for (a, b, n) in pieces:
    f = (lambda a_: (lambda t: mp.erfc(t + a_) * mp.exp((t + a_)**2)))(a)
    starts.append(len(allc))
    coeffs, err = mp.chebyfit(f, [0, b - a], n + 1, error=True)
    coeffs = coeffs[::-1]
    rc = [float(c) for c in coeffs]
    # the two leading coefficients are stored as double-doubles
    lo0, lo1 = float(coeffs[0] - rc[0]), float(coeffs[1] - rc[1])
    los += [lo0, lo1]
    ec = [mpf(rc[0]) + lo0, mpf(rc[1]) + lo1] + [mpf(c) for c in rc[2:]]
    worst = mpf(0)
    for i in range(801):
        t = (b - a) * i / 800
        fx = f(t)
        px = mpf(0)
        for c in reversed(ec): px = px * t + c
        worst = max(worst, abs((px - fx) / fx))
    print("erfc piece [%s,%s] deg %d rel err %.3e" % (mp.nstr(a, 5), mp.nstr(b, 5), n, float(worst)))
    allc += rc
emit("hidden const int __erfc_start[%d] = { %s };" % (len(pieces), ", ".join(str(s) for s in starts)))
arr("__erfc_coef", allc, per=3)
emit("/* low parts of the two leading coefficients of each piece */")
arr("__erfc_lo", los, per=2)
# x >= 6.5: erfc(x) = exp(-x^2) / x * G(1/x^2)
def G(u):
    x = 1 / mp.sqrt(u)
    return x * mp.erfc(x) * mp.exp(x * x)
fit(G, 1 / mpf("27.5")**2, 1 / mpf("6.5")**2, 14, "__erfc_asym", "x erfc(x) exp(x^2) in u = 1/x^2, 6.5 <= x <= 27.5")

# ---------------------------------------------------------------- lgamma
emit("")
euler = mp.euler
fit(lambda t: mp.loggamma(1 + t) / t if t != 0 else -euler,
    mpf("-0.25"), mpf("0.25"), 20, "__lgamma1_poly", "lgamma(1+t)/t, |t| <= 0.25")
fit(lambda t: mp.loggamma(2 + t) / t if t != 0 else 1 - euler,
    mpf("-0.75"), mpf("0.75"), 27, "__lgamma2_poly", "lgamma(2+t)/t, |t| <= 0.75")
# Stirling series coefficients B_2k / (2k (2k-1)), k = 1..10
st = [mp.bernoulli(2 * k) / (2 * k * (2 * k - 1)) for k in range(1, 11)]
arr("__stirling", st, per=3)
h, l = dd(mp.log(2 * mp.pi) / 2)
emit("hidden const double __half_log_2pi[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(mp.log(mp.pi))
emit("hidden const double __log_pi[2] = { %s, %s };" % (hexd(h), hexd(l)))
emit("hidden const double __euler_gamma = %s;" % hexd(euler))
h, l = dd(euler)
emit("hidden const double __euler_dd[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(2 / mp.pi)
emit("hidden const double __two_over_pi_dd[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(1 / mp.pi)
emit("hidden const double __inv_pi_dd[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(2 / mp.sqrt(mp.pi))
emit("hidden const double __two_over_sqrtpi[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(1 / mp.sqrt(mp.pi))
emit("hidden const double __inv_sqrtpi[2] = { %s, %s };" % (hexd(h), hexd(l)))
h, l = dd(mp.sqrt(2 / mp.pi))
emit("hidden const double __sqrt_2_over_pi[2] = { %s, %s };" % (hexd(h), hexd(l)))

# ---------------------------------------------------------------- long double
emit("")
emit("/* long double (x87 extended, 64-bit significand) constants as hex literals */")
mp.mp.dps = 80
def ext(x):
    """Round to a 64-bit significand (nearest)."""
    with mp.workprec(64):
        return +x
def ldhex(x):
    x = ext(x)
    if x == 0: return "0.0L"
    sign = "-" if x < 0 else ""
    man, e = mp.mpf(abs(x)).man_exp
    return "%s0x%xp%dL" % (sign, int(man), int(e))
def ldd(x):
    h = ext(x)
    return h, ext(x - h)
def trunc_bits80(x, bits):
    m, e = mp.frexp(x)
    m = mp.floor(m * 2**bits) / 2**bits
    return mp.ldexp(m, e)
pio2 = mp.pi / 2
# pi/2 in 32-bit pieces: n * piece is exact for |n| < 2^32
q1 = trunc_bits80(pio2, 32)
q2 = trunc_bits80(pio2 - q1, 32)
q3 = trunc_bits80(pio2 - q1 - q2, 32)
q4 = pio2 - q1 - q2 - q3
emit("hidden const long double __pio2l_split[4] = { %s, %s, %s, %s };" % (ldhex(q1), ldhex(q2), ldhex(q3), ldhex(q4)))
h, l = ldd(pio2)
emit("hidden const long double __pio2l_dd[2] = { %s, %s };" % (ldhex(h), ldhex(l)))
h, l = ldd(mp.pi)
emit("hidden const long double __pil_dd[2] = { %s, %s };" % (ldhex(h), ldhex(l)))
emit("hidden const long double __two_over_pil = %s;" % ldhex(2 / mp.pi))
h, l = ldd(1 / mp.log(2))
emit("hidden const long double __log2el[2] = { %s, %s };" % (ldhex(h), ldhex(l)))
h, l = ldd(mp.log(10, 2))
emit("hidden const long double __log2_10l[2] = { %s, %s };" % (ldhex(h), ldhex(l)))
h, l = ldd(mp.log(2))
emit("hidden const long double __ln2l[2] = { %s, %s };" % (ldhex(h), ldhex(l)))
h, l = ldd(mp.log10(2))
emit("hidden const long double __log10_2l[2] = { %s, %s };" % (ldhex(h), ldhex(l)))
# 2^(-j/64), j = -32..32, as extended double-double (for powl)
emit("/* 2^(-j/64) for j = -32..32 as (hi, lo) extended pairs, index j + 32 */")
emit("hidden const long double __exp2l_tab[130] = {")
for j in range(-32, 33):
    h, l = ldd(mp.power(2, -mpf(j) / 64))
    emit("\t%s, %s," % (ldhex(h), ldhex(l)))
emit("};")

open("src/math/math_data.c", "w").write("\n".join(out) + "\n")
print("wrote src/math/math_data.c")
