#!/usr/bin/env python3
"""Regenerates src/ctype/unicode_data.c from Python's Unicode database.

Character classes (documented in README):
  alpha  general categories L*, Nl, Mn, Mc  (letters, letter numbers and
         the combining marks that are part of words)
  upper  Lu, Lt and every character with a different simple lowercase
  lower  Ll and every character with a different simple uppercase
  space  White_Space characters except the no-break spaces (U+00A0,
         U+2007, U+202F), which must not split words
  cntrl  Cc, U+2028, U+2029
  punct  graphic characters that are not alphanumeric
  graph  everything assigned except Cc, Cs, Zs, Zl, Zp and noncharacters
  print  graph plus Zs (spaces that occupy a column)
  digit/xdigit are ASCII-only, as ISO C requires.
Case mapping uses simple (one-to-one) mappings only.
wcwidth: -1 for controls, 0 for combining/format/zero-width, 2 for East
Asian Wide/Fullwidth (and unassigned CJK blocks), 1 otherwise.
"""
import unicodedata, sys

MAXCP = 0x110000
def cat(c): return unicodedata.category(chr(c))

def ranges(pred):
    out = []
    start = None
    for c in range(MAXCP):
        if pred(c):
            if start is None: start = c
        elif start is not None:
            out.append((start, c - 1)); start = None
    if start is not None: out.append((start, MAXCP - 1))
    return out

def is_assigned(c): return cat(c) != 'Cn'
NBSP = {0xA0, 0x2007, 0x202F}
def is_space(c):
    ch = chr(c)
    if c in NBSP: return False
    return ch.isspace() and cat(c) in ('Zs', 'Zl', 'Zp', 'Cc')
def is_alpha(c):
    if c < 128: return chr(c).isalpha()
    return cat(c)[0] == 'L' or cat(c) in ('Nl', 'Mn', 'Mc')
def lower_of(c):
    s = chr(c).lower()
    return ord(s) if len(s) == 1 else c
def upper_of(c):
    s = chr(c).upper()
    return ord(s) if len(s) == 1 else c
def is_upper(c): return cat(c) in ('Lu', 'Lt') or lower_of(c) != c
def is_lower(c): return cat(c) == 'Ll' or upper_of(c) != c and cat(c) != 'Lt'
def is_cntrl(c): return cat(c) == 'Cc' or c in (0x2028, 0x2029)
def is_graph(c):
    k = cat(c)
    if k in ('Cc', 'Cs', 'Cn', 'Zs', 'Zl', 'Zp'): return False
    if (c & 0xFFFE) == 0xFFFE or 0xFDD0 <= c <= 0xFDEF: return False
    return True
def is_print(c): return is_graph(c) or cat(c) == 'Zs'
def is_punct(c): return is_graph(c) and not is_alpha(c) and not (48 <= c <= 57) and cat(c) != 'Nd'

def width(c):
    if c == 0: return 0
    k = cat(c)
    if k == 'Cc': return -1
    if k in ('Mn', 'Me', 'Cf') and c != 0xAD: return 0
    if 0x1160 <= c <= 0x11FF or c == 0x200B: return 0
    if unicodedata.east_asian_width(chr(c)) in ('W', 'F'): return 2
    if k == 'Cn' and (0x20000 <= c <= 0x3FFFD or 0x3400 <= c <= 0x4DBF or 0x4E00 <= c <= 0x9FFF): return 2
    return 1

def emit_ranges(name, rs):
    lines = ["static const struct urange %s[%d] = {" % (name, len(rs))]
    row = []
    for a, b in rs:
        row.append("{0x%X,0x%X}" % (a, b))
        if len(row) == 6:
            lines.append("\t" + ", ".join(row) + ","); row = []
    if row: lines.append("\t" + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)

def case_runs(f):
    """Runs (start, count, delta, stride) where c -> c+delta for c in a run."""
    pairs = [(c, f(c) - c) for c in range(MAXCP) if f(c) != c]
    runs = []
    i = 0
    while i < len(pairs):
        c, d = pairs[i]
        # try stride 1 or 2
        best = (1, 1)
        for stride in (1, 2):
            j = i
            while j + 1 < len(pairs) and pairs[j+1][1] == d and pairs[j+1][0] == pairs[j][0] + stride:
                j += 1
            if j - i + 1 > best[0]: best = (j - i + 1, stride)
        n, stride = best
        runs.append((c, n, d, stride))
        i += n
    return runs

def emit_case(name, runs):
    lines = ["static const struct ucase %s[%d] = {" % (name, len(runs))]
    row = []
    for c, n, d, s in runs:
        row.append("{0x%X,%d,%d,%d}" % (c, n, d, s))
        if len(row) == 5:
            lines.append("\t" + ", ".join(row) + ","); row = []
    if row: lines.append("\t" + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)

parts = []
parts.append("""/*
 * lib-spfxd — Unicode character data for <wctype.h> and wcwidth.
 * Generated by tools/gen-unicode.py from the Unicode %s database; see
 * that script for the exact class definitions.  Do not edit.
 */
#include <stdint.h>
#include "libc.h"

struct urange { uint32_t lo, hi; };
struct ucase { uint32_t start; uint16_t count; int32_t delta; uint8_t stride; };
""" % unicodedata.unidata_version)
props = [
    ("alpha_r", is_alpha),
    # only the cased letters a case mapping does not already identify
    ("upper_r", lambda c: is_upper(c) and lower_of(c) == c),
    ("lower_r", lambda c: is_lower(c) and upper_of(c) == c),
    ("space_r", is_space), ("cntrl_r", is_cntrl), ("punct_r", is_punct),
    ("graph_r", is_graph), ("zs_r", lambda c: cat(c) == "Zs"),
]
for name, pred in props:
    parts.append(emit_ranges(name, ranges(pred)))
parts.append(emit_ranges("zero_width_r", ranges(lambda c: width(c) == 0 and c != 0)))
parts.append(emit_ranges("wide_r", ranges(lambda c: width(c) == 2)))
parts.append(emit_case("toupper_t", case_runs(upper_of)))
parts.append(emit_case("tolower_t", case_runs(lower_of)))
# map_case is used by __uni_upper/__uni_lower, so emit it before them
parts.append("""
static int in_ranges(const struct urange *r, size_t n, uint32_t c)
{
	size_t lo = 0, hi = n;
	while (lo < hi) {
		size_t mid = (lo + hi) / 2;
		if (c < r[mid].lo) hi = mid;
		else if (c > r[mid].hi) lo = mid + 1;
		else return 1;
	}
	return 0;
}

static uint32_t map_case(const struct ucase *t, size_t n, uint32_t c)
{
	size_t lo = 0, hi = n;
	while (lo < hi) {
		size_t mid = (lo + hi) / 2;
		if (c < t[mid].start) hi = mid;
		else if (c >= t[mid].start + (uint32_t)t[mid].count * t[mid].stride) lo = mid + 1;
		else {
			if ((c - t[mid].start) % t[mid].stride) return c;
			return (uint32_t)((int32_t)c + t[mid].delta);
		}
	}
	return c;
}

#define N(a) (sizeof(a) / sizeof((a)[0]))
hidden int __uni_alpha(uint32_t c) { return in_ranges(alpha_r, N(alpha_r), c); }
hidden int __uni_upper(uint32_t c)
{
	return map_case(tolower_t, N(tolower_t), c) != c || in_ranges(upper_r, N(upper_r), c);
}
hidden int __uni_lower(uint32_t c)
{
	return map_case(toupper_t, N(toupper_t), c) != c || in_ranges(lower_r, N(lower_r), c);
}
hidden int __uni_space(uint32_t c) { return in_ranges(space_r, N(space_r), c); }
hidden int __uni_cntrl(uint32_t c) { return in_ranges(cntrl_r, N(cntrl_r), c); }
hidden int __uni_punct(uint32_t c) { return in_ranges(punct_r, N(punct_r), c); }
hidden int __uni_graph(uint32_t c) { return in_ranges(graph_r, N(graph_r), c); }
hidden int __uni_print(uint32_t c) { return in_ranges(graph_r, N(graph_r), c) || in_ranges(zs_r, N(zs_r), c); }
hidden uint32_t __uni_toupper(uint32_t c) { return map_case(toupper_t, N(toupper_t), c); }
hidden uint32_t __uni_tolower(uint32_t c) { return map_case(tolower_t, N(tolower_t), c); }
hidden int __uni_width(uint32_t c)
{
	if (c < 0x20 || (c >= 0x7f && c < 0xa0)) return c ? -1 : 0;
	if (c < 0x300) return 1;
	if (in_ranges(zero_width_r, N(zero_width_r), c)) return 0;
	if (in_ranges(wide_r, N(wide_r), c)) return 2;
	return 1;
}
""")
open("src/ctype/unicode_data.c", "w").write("\n".join(parts))
print("ok")
