#!/bin/sh
# Regenerates arch/<arch>/include/bits/syscall.h from the Linux kernel UAPI
# headers (the syscall numbers are the kernel's ABI; nothing here comes from
# a C library).
#
#   tools/gen-syscall.sh x86_64  [cc]     (default cc: gcc)
#   tools/gen-syscall.sh aarch64 [cc]     (default cc: aarch64-linux-gnu-gcc)
#
# The UAPI <asm/unistd.h> is run through the target's preprocessor and every
# __NR_ macro is expanded and evaluated, so indirections such as the generic
# table's __NR3264_* names resolve to plain numbers.
arch=${1:-x86_64}
case $arch in
	x86_64)  cc=${2:-gcc} ;;
	aarch64) cc=${2:-aarch64-linux-gnu-gcc} ;;
	*) echo "unknown arch $arch" >&2; exit 1 ;;
esac
out=arch/$arch/include/bits/syscall.h
tmp=$(mktemp -d) || exit 1
trap 'rm -rf "$tmp"' EXIT
printf '#include <asm/unistd.h>\n' > "$tmp/u.c"
"$cc" -E -dM "$tmp/u.c" | sed -n 's/^#define __NR_\([a-z0-9_]*\) .*/\1/p' | sort -u > "$tmp/names"
{ printf '#include <asm/unistd.h>\n'; while read -r n; do printf 'NR %s __NR_%s\n' "$n" "$n"; done < "$tmp/names"; } > "$tmp/e.c"
"$cc" -E -P "$tmp/e.c" | python3 -c '
import sys, re
rows = []
for line in sys.stdin:
    if not line.startswith("NR "): continue
    _, name, expr = line.split(" ", 2)
    expr = expr.strip()
    if not re.fullmatch(r"[0-9()+ ]+", expr): continue      # skip non-numeric
    rows.append((eval(expr), name))
rows.sort()
arch = sys.argv[1]
print("/* Linux %s system call numbers (kernel ABI).  Generated by tools/gen-syscall.sh. */" % arch)
print("#ifndef _BITS_SYSCALL_H\n#define _BITS_SYSCALL_H\n")
for num, name in rows: print("#define __NR_%-26s %d" % (name, num))
print()
for num, name in rows: print("#define SYS_%-27s __NR_%s" % (name, name))
print("\n#endif")
' "$arch" > "$out"
echo "wrote $out ($(grep -c '^#define SYS_' "$out") syscalls)"
