#!/bin/sh
# Regenerates arch/x86_64/include/bits/syscall.h from the Linux kernel UAPI
# header (the syscall numbers are the kernel's ABI; nothing here comes from a
# C library).  Usage: tools/gen-syscall.sh [path/to/asm/unistd_64.h]
src=${1:-/usr/include/x86_64-linux-gnu/asm/unistd_64.h}
out=arch/x86_64/include/bits/syscall.h
{
  echo "/* Linux x86-64 system call numbers (kernel ABI).  Generated by tools/gen-syscall.sh. */"
  echo "#ifndef _BITS_SYSCALL_H"
  echo "#define _BITS_SYSCALL_H"
  echo
  sed -n 's/^#define __NR_\([a-z0-9_]*\)[ \t]*\([0-9][0-9]*\)$/\1 \2/p' "$src" |
    while read -r name num; do
      printf '#define __NR_%-26s %s\n' "$name" "$num"
    done
  echo
  sed -n 's/^#define __NR_\([a-z0-9_]*\)[ \t]*\([0-9][0-9]*\)$/\1/p' "$src" |
    while read -r name; do
      printf '#define SYS_%-27s __NR_%s\n' "$name" "$name"
    done
  echo
  echo "#endif"
} > "$out"
echo "wrote $out"
