#!/usr/bin/env python3
"""
lib-spfxd — generate src/math/ldbl128_data.h, the constant tables of the
IEEE binary128 long double functions (src/math/ldbl128.c).

Every value is evaluated with mpmath at 400 bits and written as a
double-binary128 pair hi + lo: hi is the value rounded to nearest at 113
bits (or fewer, where a product with a small integer must be exact) and
lo is the rest, rounded to 113 bits.  Hex float literals are exact, so the
compiler does no decimal conversion.

    python3 tools/gen-ldbl128.py > src/math/ldbl128_data.h
"""
import mpmath as mp

mp.mp.prec = 400


def rnd(x, bits):
    """x rounded to nearest-even with `bits` significant bits."""
    if x == 0:
        return mp.mpf(0)
    m, e = mp.frexp(x)                  # x = m 2^e, 0.5 <= |m| < 1
    scaled = mp.ldexp(m, bits)
    n = int(mp.nint(scaled))
    return mp.ldexp(n, e - bits)


def hexq(x):
    """Exact C hex literal (long double) for a value with <= 113 bits."""
    if x == 0:
        return "0.0L"
    s = "-" if x < 0 else ""
    x = abs(x)
    m, e = mp.frexp(x)                  # x = m 2^e
    n = int(mp.ldexp(m, 116))           # 116 bits: whole hex digits
    assert mp.ldexp(n, e - 116) == x, "value has more than 116 bits"
    # write as 0x<n>p<e-116>, then normalize to 0x1.xxxx form
    # n has exactly 116 bits, top bit set: n = 1.f * 2^115
    frac = n - (1 << 115)
    digits = "%029x" % (frac << 1)      # 115 fraction bits -> pad to 116 = 29 hex
    digits = digits.rstrip("0") or "0"
    return "%s0x1.%sp%+dL" % (s, digits, e - 1)


def pair(x, hibits=113):
    hi = rnd(x, hibits)
    lo = rnd(x - hi, 113)
    return hi, lo


def emit_pair(name, x, hibits=113, comment=""):
    hi, lo = pair(x, hibits)
    c = "\t/* %s */" % comment if comment else ""
    print("static const long double %s[2] = { %s, %s };%s" % (name, hexq(hi), hexq(lo), c))


def emit_table(name, vals, comment):
    print("/* %s */" % comment)
    print("static const long double %s[%d][2] = {" % (name, len(vals)))
    for v in vals:
        hi, lo = pair(v)
        print("\t{ %s, %s }," % (hexq(hi), hexq(lo)))
    print("};")
    print()


print("/* Generated by tools/gen-ldbl128.py — do not edit. */")
print()
ln2 = mp.log(2)
emit_pair("LN2", ln2, 97, "ln 2; hi has 97 bits so k*hi is exact for |k| < 2^16")
emit_pair("LN2_64", ln2 / 64, 90, "ln(2)/64; hi has 90 bits so n*hi is exact for |n| < 2^23")
print("static const long double INV_LN2_64 = %s;\t/* 64/ln 2 */" % hexq(rnd(64 / ln2, 113)))
emit_pair("LOG2E", 1 / ln2, 113, "1/ln 2")
emit_pair("LOG10E", 1 / mp.log(10), 113, "1/ln 10")
emit_pair("LN10", mp.log(10), 113, "ln 10")
emit_pair("LOG10_2", mp.log10(2), 113, "log10(2)")
emit_pair("PIO2", mp.pi / 2, 113, "pi/2")
emit_pair("PI", mp.pi, 113, "pi")
print()
emit_table("EXP2_T", [mp.power(2, mp.mpf(j) / 64) for j in range(64)], "2^(j/64), j = 0..63")
emit_table("LOG_T", [mp.log(1 + mp.mpf(j) / 128) for j in range(129)], "ln(1 + j/128), j = 0..128")
emit_table("ATAN_T", [mp.atan(mp.mpf(j) / 64) for j in range(65)], "atan(j/64), j = 0..64")


def emit_coeffs(name, vals, comment):
    print("/* %s */" % comment)
    print("static const long double %s[%d] = {" % (name, len(vals)))
    for v in vals:
        print("\t%s," % hexq(rnd(v, 113)))
    print("};")
    print()


# Taylor coefficients (the truncation errors are bounded in ldbl128.c)
emit_coeffs("EXP_C", [1 / mp.factorial(n) for n in range(2, 15)], "1/n!, n = 2..14")
emit_coeffs("SIN_C", [(-1) ** k / mp.factorial(2 * k + 1) for k in range(1, 15)],
            "(-1)^k/(2k+1)!, k = 1..14")
emit_coeffs("COS_C", [(-1) ** k / mp.factorial(2 * k) for k in range(2, 16)],
            "(-1)^k/(2k)!, k = 2..15")
emit_coeffs("ATANH_C", [mp.mpf(1) / (2 * k + 1) for k in range(1, 8)], "1/(2k+1), k = 1..7")
emit_coeffs("ATAN_C", [mp.mpf(-1) ** k / (2 * k + 1) for k in range(1, 10)], "(-1)^k/(2k+1), k = 1..9")
